# Generated by Django 5.0.1 on 2024-01-09 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Choicee',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='Questionn',
        ),
    ]
