# Generated by Django 5.0.1 on 2024-01-09 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choice_choicee_rename_question_questionn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choicee',
            new_name='Choice',
        ),
        migrations.RenameModel(
            old_name='Questionn',
            new_name='Question',
        ),
    ]
